#!/usr/bin/env bash

# Copy the examples file
cp common/src/main/resources/properties/server.properties.example common/src/main/resources/properties/server.properties

# Fill in blanks in server.properties w/ environment variables
python ./deploy.py

# Build fat jar with Maven
mvn -B clean verify

# Output:
# service/target/service-1.0-SNAPSHOT-jar-with-dependencies.jar
#
# Example:
# java -jar service/target/service-1.0-SNAPSHOT-jar-with-dependencies.jar
