INSERT INTO schools (name, address, country, library_status) VALUES ('All Saints Secondary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Antigua Girls High School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Antigua Wesleyan Junior Academy', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bendals Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Boys Training School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Buckleys Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Cedar Grove Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Clare Hall Secondary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Charlesworth T. Samuel John Hughes Primary', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Environmental Awareness Group', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Five Islands Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Freeman''s Ville Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Freetown Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Glanvilles Secondary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Golden Grove Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Green Bay Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Holy Trinity Primary School (Barbuda)', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Irene B. Williams Secondary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Jennings Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Jennings Secondary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('J.T. Ambrose Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Kids Unlimited', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Liberta Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Mary E. Pigott Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('New Bethel SDA Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('New Winthorpes Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Newfields Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Old Road Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Olivia David Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Ottos Comprehensive Secondary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Pares Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Pares Secondary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Parham Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Potters Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Princess Margaret Secondary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Project Hope', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Andrew''s School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. John''s Catholic Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. John''s Lutheran Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Mary''s Secondary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Nicholas'' Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Sir McChesney George Secondary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Sir Novelle Richards Academy', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Student Support Centre', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('T.N. Kirnon Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Urlings Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Victory Center', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Villa Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Willikies Primary School', '', 'ANTIGUA_AND_BARBUDA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Achievement Learning Centre', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Arthur Waldron SDA Academy', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Atkinson Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bagatelle Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Baroness Patricia Scotland Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Beau Bois Pre-School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Belles Primary', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bellevue Chopin Primary', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bense Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Berean Christian Academy', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Calibishie Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('CALLS', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Campbell Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Canefield Pre-School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Castle Bruce Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Castle Bruce Secondary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Charlotte''s Pre-School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Christian Union Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Clifton Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Colihaut Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Concord Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Cottage Pre-School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Coulibistrie Pre-School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Coulibistrie Primary', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Delices Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Dominica Community High School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Dominica Grammar School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Dos D'' Ane Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Dublanc Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Dominica Youth Business Trust', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Feed My Sheep', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Giraudel Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Goodwill Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Goodwill Secondary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Grand Bay Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Grand Fond Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Gregor Nassief Pocket Library Project', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Irie Eco Children''s Program', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Isaiah Thomas Secondary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Isulukati Special Education School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Jinja Pre-School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Jones Beaupierre Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Kelleb John Laurent Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Laudat Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Love One Teach One Foundation', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Mahaut Primary School School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Mahaut Pre-School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Mahaut River Pre-School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Massacre/Canefield Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Massacre Pre-School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Morne Jaune Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Morne Prosper Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Newtown Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Northeast Comprehensive Secondary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Orion Academy', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Paix Bouche Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Penville Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Petite Savanne Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Pierre Charles Secondary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Pioneer Preparatory School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Pioneer Prep Pre-School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Portsmouth Secondary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Roosevelt Douglas Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Roseau Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Roseau Public Library', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Salybia Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Salisbury Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('San Sauveur Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Savanne Paille Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Sheba Pre-School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Sineku Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Soufriere Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. John''s Academy', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. John''s RC Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Joseph SDA Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Luke''s Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Martin Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Martin Secondary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Mary''s Academy', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Mary''s Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Temple SDA Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Tete Morne Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Thibaud Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Trafalgar Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Tunubuku Reference Library', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Warner Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Wesley Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Willis Strathmore Stevens Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Woodfordhill Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Wotten Waven Primary School', '', 'DOMINICA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Anglican High School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Beacon Learning Centre', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Beaulieu RC Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Blessed Sacrament RC Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Boca Secondary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bonair Government School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Chantimelle Roman Catholic School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Concord Government School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Constantine Methodist Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Corinth Government Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Dover Government School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Florida Government School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Grand Roy Government School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Grenada Boys Secondary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Grenada Christian Academy', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Grenada School for Special Education', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Grenada SDA Comprehensive Secondary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Grenville Secondary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Happy Hill Secondary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Harvey Vale Government School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Hillsborough Government School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Hillsborough Secondary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Holy Cross RC School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Hope Pals', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('J. W. Fletcher Catholic Secondary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('L''Esterre Rosary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Limes Government Pre-School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('MacDonald College', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Grenada Community Library', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Mt. Airy Young Readers Program', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Mt. Moritz Anglican School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Mt. Pleasant Government School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Mt. Rose SDA Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Nation Builders', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Paraclete Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Programme for Adolescent Mothers (Mt. Parnassus)', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Programme for Adolescent Mothers (Pearls)', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('River Sallee Government Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Rose Hill Infant School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Roving Caregivers', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Samaritan Presbyterian Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Andrew''s Anglican Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Andrew''s Anglican Secondary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Andrew''s Methodist Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. David''s Catholic Secondary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. David''s RC Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Dominic''s RC Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. George''s Anglican Junior School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. George’s Anglican Senior School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. George''s SDA Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Giles Anglican School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. John''s Christian Secondary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Joseph''s Catholic Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Joseph''s Convent (Grenville)', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Joseph''s Convent (St. George''s)', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Joseph''s RC Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Louis RC Girls Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Mark''s Secondary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Mary''s RC Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Martin de Porres RC Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Michael''s RC Infant School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Mathews RC Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Michael''s RC Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Patrick''s Anglican Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Patrick''s RC Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Peter''s RC Primary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Rose Modern Secondary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Theresa''s RC School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Sunnyside School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Uganda Martyrs Catholic School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Vendome RC School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Victoria School for Special Education', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Wesley College', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Westerhall Secondary School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Windsor Forest Pre-School', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('YWCA', '', 'GRENADA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Blanket Night', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Cecele Brown Integrated School', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Charlestown Library', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Charlestown Primary School', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Charlestown Secondary School', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Elizabeth Pemberton Primary School', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Joycelyn Liburd Primary School', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Gingerland Public Library', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Gingerland Secondary School', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Ivor Walters Primary School', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Nevis Academy', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Operation Future', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. James Primary School', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Thomas'' Primary School', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Violet O. Jeffers-Nichols Primary School', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Tyrell Williams Primary School', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Verchilds High School', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Violet Petty Primary School', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Washington Archibald High School', '', 'ST_KITTS_AND_NEVIS', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Anse Ger Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Anse La Raye Infant School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Anse La Raye Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Augier Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Aux Lyons Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Ave Maria RC Infant School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Ave Maria RC Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Babonneau Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Babonneau Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Balata Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Banse la Grace Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Beanefield Comprehensive Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Belle Vue Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bexon Infant School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bexon Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Blanchard Primary', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bocage Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bonne Terre Prepatory School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bouton RC Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Canaries Infant School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Canaries Public Lirary', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Cannon Laurie Anglican Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Castries Anglican Infant School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Central Library of St. Lucia', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Centre For Adolescent Renewal and Education (CARE)', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Children''s Literacy Action Programme', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Ciceron RC Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Ciceron Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Choiseul Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Clendon Mason Memorial Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Corinth Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Court Diversion Programme', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Dame Pearlette Louisy Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Delcer RC Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Dennery Infant School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Dennery Pre-School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Dennery Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Derniere Riviere Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Desruisseaux Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Des Barras Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Dugard Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Entrepot Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Fay Stars Sports & Youth Club', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Fond Assau Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Fond St. Jacques Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Forestiere Methodist Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Fortuna Anthony Pre-Schools', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Grace RC Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Grande Riviere Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Gros Islet Infant School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Gros Islet Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Gros Islet Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Kiddy''s Homey Day Care', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Kid''s Step DC', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('L''Abayee SDA Primary School  198', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('La Croix Maingot Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Lady Gordon Opportunity Centre', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('La Guerre Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('La Ressource RC Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Laborie RC Boys Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Laborie RC Girls Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Marchand RC Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Micoud Public Library', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Micoud Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Micoud Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Millet Infant School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Millet Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Mirja Sachs Pre-School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Mon Repos Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Monchy RC Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Mongouge Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Montessori School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Morne Du Don Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Odsan Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Piaye Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Piaye Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Plain View Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Reunion Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Riviere Doree Anglican School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Roblot Commuinty Library', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Roblot Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Richfond Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Roseau RC Combined School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Saltibus RC Combined Shool', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Aloysius RC Boys Infant School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Aloysius RC Boys Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Sir Ira Simmons Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Soufriere Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Soufriere Public Library', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Soufriere Infant School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Soufriere Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Soufriere Special Education & Rehabilitation Centre', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Stanley Jon Odlum Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Tapion School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Ti Rocher RC Primary School (Castries)', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Vide Bouteille Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Vide Bouteille Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Beanefield Comprehensive Secondary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Vieux Fort Comprehensive Secondary School, Campus B', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Vieux Fort Infant School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Vieux Fort Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Vieux Fort Special Education School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Vieux Fort Public Library', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Vige Primary School', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Wiltons Yard Association', '', 'ST_LUCIA', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Adelphi Secondary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Argyle RC Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Barrouallie Anglican Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Barrouallie Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Belmont Government Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bequia Anglican Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bequia Community High School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bequia Reading Group', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bequia SDA Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bequia SDA Secondary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bethel High School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Bethel Pre-School (Fitz-Hughes)', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Biabou Methodist Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Brighton Methodist School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Brighton Reading Group', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Buccament Bay Secondary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Buccament Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Cane End Govt School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Calder Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Calliaqua Anglican Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Central Leeward Secondary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Chateaubelair Red Cross Pre-School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Chateaubelair Methodist Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Cheryl''s Reading Club (Bequia)', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Clare Valley Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Colonaire Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('CW Prescod Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Diamond Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Dorsetshire Hill Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Emmanuel High School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Evesham Methodist School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Fancy Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Fitz-Hughes Pre-School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Fitz-Hughes Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('George Stephens Senior Secondary', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Georgetown Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Georgetown Secondary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Golden Grove Pre-School (Chateaubelair)', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Greggs Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Hospital Children''s Ward', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Intermediate High School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('JEMS Progressive Organization pre-School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Dr. J. P. Eustace Memorial Secondary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Evesham Methodist School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Fairhall Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Fancy Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Judy''s Pre-School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Kearton''s United Community Organization', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Kingstown Anglican School Annex', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Kingstown Anglican School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Kingstown Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Kingstown Preparatory School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Langley Park Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Lauders Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Layou Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Learning Centre (Bequia)', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Leeward District SDA Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Lodge Village Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Lower Bay Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Lowmans Leeward Anglican School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Lowmans Windward Anglican School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Mammy Joy''s Reading Group (Chateaubelair)', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Marriaqua Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Marriaqua Public Library', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Mary Hutchinson Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Mayreau Primary', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Ministry of Education, Jocelyn Blake-Brown', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Mountain View Adventist Academy', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Naima Dynamites Reading Group', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('New Grounds Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('New Prospect Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('North Union Secondary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Owia Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Paget Farm Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Pamelus Burke Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Park Hill Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Petit Bordel Secondary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Questelles Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Richland Park Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Richland Park SDA Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Rose Hall Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Sandy Bay Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Sandy Bay Secondary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('School for Children with Special Needs (Kingstown)', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Sion Hill Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('South Rivers Methodist Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Spring Village Methodist Primary', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Clair Dacon Secondary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Vincent Girls High School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('St. Vincent National Library', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Stephanie Browne Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Stubbs Goverment School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('School for Children with Special Needs (Georgetown)', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Tourama Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Troumaca Government School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Troumaca Ontario Secondary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Union Island Secondary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('Westwood Methodist Primary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
INSERT INTO schools (name, address, country, library_status) VALUES ('West St. George Secondary School', '', 'ST_VINCENT_AND_THE_GRENADINES', 'UNKNOWN');
